const mongoose = require('mongoose');

const serviceSheetSchema = new mongoose.Schema({
  issue_type: Number,
  plant_info: String,
  doc_no: String,
  visit_date: Date,
  company_name: String,
  address: String,
  contact_person: String,
  mobile_no: String,
  email_id: String,
  visit_purpose: String,
  ser_quarterly: Boolean,
  ser_emergency: Boolean,
  ser_ad_hoc: Boolean,
  ser_client_call: Boolean,
  ser_module_cleaning: Boolean,
  dc_module_earthing: Boolean,
  dc_fuse: Boolean,
  dc_mc4_connector: Boolean,
  dc_loose_wires: Boolean,
  dc_voltage: Boolean,
  dc_current: Boolean,
  dc_loose_connection: Boolean,
  ac_line_voltage: Boolean,
  ac_line_current: Boolean,
  ac_pn_voltage: Boolean,
  ac_islanding_test: Boolean,
  ac_loose_connection: Boolean,
  earthing_resistance: Boolean,
  auto_timer_program: Boolean,
  auto_sprinkler: Boolean,
  auto_solenoid_valve: Boolean,
  mount_mid_clamp: Boolean,
  mount_end_clamp: Boolean,
  mount_spring_nut: Boolean,
  mount_intensity_strength: Boolean,
  mount_corrosion: Boolean,
  thermo_hotspot_modules: Boolean,
  thermo_hotspot_inverter: Boolean,
  thermo_hotspot_switchgear: Boolean,
  other_fault_analysis: String,
  other_function_check: String,
  misc_cable_tie: Boolean,
  misc_safety_signs: Boolean,
  misc_anti_rust_paint: Boolean,
  rn_ry: Number,
  yn_yb: Number,
  bn_rb: Number,
  ng: Number,
  remarks: String,
  company_rep_name: String,
  company_rep_signature: String,
  maintenance_provider_name: String,
  maintenance_provider_signature: String,
  company_stamp: String,
  status: {
    type: String,
    enum: ['approved', 'pending', 'rejected'],
    default: 'pending'
  }

});

module.exports = mongoose.model('ServiceSheet', serviceSheetSchema);
